DROP DATABASE IF EXISTS test_db;

CREATE DATABASE test_db;

USE test_db;

CREATE TABLE mapset (
id INT NOT NULL AUTO_INCREMENT,
loc VARCHAR(30) NOT NULL,
spr VARCHAR(30) NOT NULL,
def VARCHAR(30) NOT NULL,
res VARCHAR(30) NOT NULL,
own VARCHAR(30),
PRIMARY KEY (id)
);